services:
  vi-upper:
    build: .
    container_name: vi-upper
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - SOURCE_BUCKET=${SOURCE_BUCKET}
      - TARGET_BUCKET=${TARGET_BUCKET}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=INFO
    volumes:
      - ./temp:/app/temp
    labels:
      - traefik.enable=true
      - traefik.http.routers.vi-upper.rule=Host(`${API_DOMAIN}`)
      - traefik.http.routers.vi-upper.entrypoints=websecure
      - traefik.http.routers.vi-upper.tls.certresolver=myresolver
      - traefik.http.routers.vi-upper.middlewares=vi-upper-headers@docker
      - traefik.http.middlewares.vi-upper-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.vi-upper-headers.headers.STSSeconds=315360000
      - traefik.http.middlewares.vi-upper-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.vi-upper-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.vi-upper-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.vi-upper-headers.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.vi-upper-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.vi-upper-headers.headers.STSPreload=true
    networks:
      - web

networks:
  web:
    external: true