services:
  video-merger-api:
    build: .
    ports:
      - "127.0.0.1:8000:8000"  # Optional: for direct access
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - SOURCE_BUCKET=${SOURCE_BUCKET}
      - TARGET_BUCKET=${TARGET_BUCKET}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=INFO
    volumes:
      - ./temp:/app/temp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.video-merger-api.rule=Host(`${API_HOST}`)'
      - 'traefik.http.routers.video-merger-api.entrypoints=websecure'
      - 'traefik.http.routers.video-merger-api.tls=true'
      - 'traefik.http.routers.video-merger-api.tls.certresolver=mytlschallenge'  # Match your Traefik config
      - 'traefik.http.services.video-merger-api.loadbalancer.server.port=8000'
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  temp: